mod 'boxen', '2.1.0', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '4.0.0', :github_tarball => 'puppetlabs/puppetlabs-stdlib'
mod 'homebrew', '1.1.2', :github_tarball => 'boxen/puppet-homebrew'
mod 'xquartz', '1.1.0', :github_tarball => 'boxen/puppet-xquartz'
